In [1]:
import numpy as np

In [2]:
#1. Create a null array of size 10 but the fifth value which is 1

#one way
v1 = np.array([0]*4+[1]+[0]*5)
print(v1)

#another way
v2= np.zeros(shape=(10,), dtype=int)
v2[4]=1
print(v2)

[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [3]:
#2. Reverse a above created array (first element becomes last)

v1[::-1]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

w = [1,2,0,0,4,0]
non_zero_index_list = [] # the list that contains the indices in w that have non-zero values
for i in range(len(w)):
    if w[i] != 0:
        non_zero_index_list.append(i)
non_zero_index_list

[0, 1, 4]

In [6]:
#5. Create a 3x3x3 array with random values

np.random.random((3, 3, 3)) # 3x3x3 matrix with random values

array([[[0.34203538, 0.93930857, 0.03110791],
        [0.40206938, 0.5141383 , 0.79342071],
        [0.16505226, 0.98776339, 0.85322947]],

       [[0.05616469, 0.1918185 , 0.58427478],
        [0.72421116, 0.42344424, 0.46957196],
        [0.99137007, 0.8267297 , 0.51796517]],

       [[0.4418698 , 0.94328506, 0.04131554],
        [0.9488572 , 0.93475477, 0.06675357],
        [0.35910826, 0.49945405, 0.84540754]]])

In [7]:
#6. Create a 10x10 array with random values and find the minimum and maximum values

temp = np.random.random((10, 10))  # 10x10 matrix with random values
#print(temp)
print(f"Min value is {np.min(temp)}")
print(f"Max value is {np.max(temp)}")


Min value is 0.004207029594313183
Max value is 0.997952723208971


In [8]:
#7. Create a random vector of size 30 and find the mean value

temp = np.random.random((30,))
#print(temp)
print(f"Mean value is {np.mean(temp)}")

Mean value is 0.6058872601087042


In [9]:
#8. Create a 2d array with 1 on the border and 0 inside

num_rows = 5 # number of rows
num_cols = 6 # number of columns
temp = np.zeros(shape=(num_rows,num_cols), dtype=int) # creates a matrix with zeros everywhere
temp[0,] = np.ones(shape=(num_cols,), dtype=int) # writes ones to first row
temp[num_rows - 1,] = np.ones(shape=(num_cols,), dtype=int) # writes ones to last row
temp[:,0] = np.transpose(np.ones(shape=(num_rows,), dtype=int)) # writes ones to first column
temp[:,num_cols - 1] = np.transpose(np.ones(shape=(num_rows,), dtype=int)) # writes ones to first column
temp

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [10]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

# A is the 5x3 matrix
A = np.random.randint(0,10,(5,3))
print(A)
# B is the 3x2 matrix
B = np.random.randint(0,10,(3,2))
print(B)
# C is the matrix product
C = np.matmul(A, B)
print(C)

[[1 9 7]
 [8 3 9]
 [4 4 5]
 [2 2 6]
 [5 0 0]]
[[1 9]
 [0 6]
 [8 2]]
[[ 57  77]
 [ 80 108]
 [ 44  70]
 [ 50  42]
 [  5  45]]


In [11]:
#10. Extract the integer part of a random array

temp = np.random.random(size=(2,3)) * 100 # the random array
print(temp)
f = lambda x: x//1
np.array(f(temp), dtype=int)

[[69.08724475 33.28063532 58.90992374]
 [ 7.87117814 51.41617499 67.71383985]]


array([[69, 33, 58],
       [ 7, 51, 67]])

In [12]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4

# "row values" is confusing. Shuld "row values" be just "values"?
np.random.randint(low=0, high=5, size=(5,5))

array([[1, 3, 1, 1, 0],
       [4, 1, 3, 4, 2],
       [4, 4, 3, 1, 4],
       [4, 3, 3, 0, 4],
       [0, 4, 4, 2, 0]])

In [13]:
#12.  Create a random vector of size 10 and sort it

temp = np.random.random(10) # the random vector 
np.sort(temp)               # the sorted vector

array([0.10483717, 0.16444101, 0.21967765, 0.22308467, 0.25774938,
       0.4594553 , 0.50821601, 0.7212689 , 0.78746071, 0.81878775])

In [14]:
#13. Consider two random array A anb B, check if they are equal.

num_elements= 2
A = np.random.randint(low=0, high=2, size=(num_elements,))
print(A)
B = np.random.randint(low=0, high=2, size=(num_elements,))
print(B)
print((A==B).all()) # returns True if A==B and False otherwise


[0 1]
[1 0]
False


In [15]:
#14. How to tell if a given 2D array has null columns?
num_rows = 2 # number of rows
num_cols = 5 # number of columns
A = np.random.randint(low=0, high=2, size=(num_rows, num_cols))  # the 2D array
print(A)
B = np.zeros(shape=(num_rows,1), dtype=int)  # all zero values
print(B)
result = np.sum(np.all(A==B, axis=0)) # computes the number of null columns in A
print(f"The number of null columns in A is {result}")

[[0 0 1 0 1]
 [1 1 1 0 1]]
[[0]
 [0]]
The number of null columns in A is 1


In [16]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?
A = np.random.randint(low=0, high=2, size=(2, 2, 2, 2))  # the 4D array
print(A)
print("-"*20)
print(np.sum(A, axis=(2,3))) # the 2D array after summing over the last two axis

[[[[0 0]
   [1 0]]

  [[0 0]
   [0 0]]]


 [[[0 1]
   [0 1]]

  [[0 0]
   [1 0]]]]
--------------------
[[1 0]
 [2 1]]


In [17]:
#16. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

# This question is slightly unclear. I assume the first matrix X is written as (A, B, C) where A, B, and C are 5x5 matrices. 
# If Y is the array with dimensions (5,5), I define the product of X and Y as (A*Y, B*Y, Z*Y), where * is the matrix
# multiplication. The result is a 5x5x3 matrix.

X = np.random.randint(low=0, high=2, size=(5, 5, 3))  # the (5,5,3) array
Y = np.random.randint(low=0, high=2, size=(5, 5))  # the (5,5) array
result = np.zeros(shape=(5,5,3), dtype=int)
result[:,:,0] = np.matmul(X[:,:,0],Y)
result[:,:,1] = np.matmul(X[:,:,1],Y)
result[:,:,2] = np.matmul(X[:,:,2],Y)
result

array([[[2, 2, 2],
        [2, 1, 2],
        [1, 2, 1],
        [2, 2, 2],
        [1, 1, 0]],

       [[2, 1, 3],
        [2, 1, 2],
        [1, 1, 3],
        [3, 2, 2],
        [1, 0, 2]],

       [[2, 3, 1],
        [2, 2, 1],
        [2, 3, 1],
        [2, 3, 1],
        [1, 2, 0]],

       [[2, 1, 4],
        [2, 1, 3],
        [1, 1, 3],
        [2, 1, 4],
        [1, 0, 2]],

       [[3, 3, 2],
        [2, 2, 1],
        [2, 2, 2],
        [3, 2, 1],
        [1, 1, 1]]])

In [18]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

X = np.random.randint(low=0, high=2, size=(10, 10))  # the (10,10) array

count = 0
for i in range(7):
    for j in range(7):
        count += 1
        print(f"Block {count} is {X[i:i+3,j:j+3]}") # there will be 49 blocks printed


Block 1 is [[1 0 0]
 [0 1 0]
 [1 1 0]]
Block 2 is [[0 0 1]
 [1 0 1]
 [1 0 0]]
Block 3 is [[0 1 1]
 [0 1 1]
 [0 0 1]]
Block 4 is [[1 1 0]
 [1 1 0]
 [0 1 1]]
Block 5 is [[1 0 1]
 [1 0 0]
 [1 1 1]]
Block 6 is [[0 1 0]
 [0 0 0]
 [1 1 1]]
Block 7 is [[1 0 1]
 [0 0 1]
 [1 1 1]]
Block 8 is [[0 1 0]
 [1 1 0]
 [1 0 1]]
Block 9 is [[1 0 1]
 [1 0 0]
 [0 1 0]]
Block 10 is [[0 1 1]
 [0 0 1]
 [1 0 0]]
Block 11 is [[1 1 0]
 [0 1 1]
 [0 0 0]]
Block 12 is [[1 0 0]
 [1 1 1]
 [0 0 0]]
Block 13 is [[0 0 0]
 [1 1 1]
 [0 0 0]]
Block 14 is [[0 0 1]
 [1 1 1]
 [0 0 0]]
Block 15 is [[1 1 0]
 [1 0 1]
 [0 1 0]]
Block 16 is [[1 0 0]
 [0 1 0]
 [1 0 1]]
Block 17 is [[0 0 1]
 [1 0 0]
 [0 1 0]]
Block 18 is [[0 1 1]
 [0 0 0]
 [1 0 1]]
Block 19 is [[1 1 1]
 [0 0 0]
 [0 1 0]]
Block 20 is [[1 1 1]
 [0 0 0]
 [1 0 0]]
Block 21 is [[1 1 1]
 [0 0 0]
 [0 0 1]]
Block 22 is [[1 0 1]
 [0 1 0]
 [1 1 1]]
Block 23 is [[0 1 0]
 [1 0 1]
 [1 1 1]]
Block 24 is [[1 0 0]
 [0 1 0]
 [1 1 0]]
Block 25 is [[0 0 0]
 [1 0 1]
 [1 0 1]]
Block 26 

In [19]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

X = np.random.randint(low=0, high=2, size=(16, 16))  # the (16,16) array
print(X)
print("--"*20)
X1, X2, X3, X4 = np.vsplit(X, [4, 8, 12])
X11, X12, X13, X14 = np.hsplit(X1, [4, 8, 12])
X21, X22, X23, X24 = np.hsplit(X2, [4, 8, 12])
X31, X32, X33, X34 = np.hsplit(X3, [4, 8, 12])
X41, X42, X43, X44 = np.hsplit(X4, [4, 8, 12])
Y = np.array([[np.sum(X11), np.sum(X12), np.sum(X13), np.sum(X14)], [np.sum(X21), np.sum(X22), np.sum(X23), np.sum(X24)], [np.sum(X31), np.sum(X32), np.sum(X33), np.sum(X34)], [np.sum(X41), np.sum(X42), np.sum(X43), np.sum(X44)]])
print(f"When the block size is 4x4, the block-sum is \n{Y}")

#print(np.arange(0, X.shape[0], 4))
#Y = np.add.reduceat(np.add.reduceat(X, np.arange(0, X.shape[0], 4), axis=0),
#                                       np.arange(0, X.shape[1], 4), axis=1)
#print(f"When the block size is 4x4, the block-sum is \n{Y}")

[[1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1]
 [1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1]
 [0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0]
 [1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 1]
 [0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1]
 [0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 1]
 [0 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0]
 [0 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1]
 [0 1 0 1 1 1 1 0 1 0 0 0 0 0 1 1]
 [1 0 0 0 1 1 1 0 1 1 0 1 0 0 0 1]
 [0 0 1 1 1 1 0 0 1 0 0 0 0 1 1 0]
 [0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 0]
 [1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0]
 [0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 1]
 [0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1]]
----------------------------------------
When the block size is 4x4, the block-sum is 
[[ 8  8 10  4]
 [ 7  9  7  8]
 [ 7 10  6  8]
 [ 6  7  8  6]]


In [20]:
#19. Calculate summary statistics: mean, std, 0%,10%,20%,…, percentiles (look for how to do that in the numpy documentation).

X = np.random.randint(low=0, high=100, size=(10,))  # the array of size 10
print(X)
print(f"The mean of X is {np.mean(X):.2f}")
print(f"The standard deviation of X is {np.std(X):.2f}")
for k in list(range(100))[::10]:
    print(f"The {k}% percentile of X is {np.percentile(X, k):.2f}")

[10 75 67 62 94 35 93 89 79 92]
The mean of X is 69.60
The standard deviation of X is 26.37
The 0% percentile of X is 10.00
The 10% percentile of X is 32.50
The 20% percentile of X is 56.60
The 30% percentile of X is 65.50
The 40% percentile of X is 71.80
The 50% percentile of X is 77.00
The 60% percentile of X is 83.00
The 70% percentile of X is 89.90
The 80% percentile of X is 92.20
The 90% percentile of X is 93.10


In [21]:
#20. Run a t-test of two Gaussian distribution means using scipy (see https://scipy-lectures.org/intro/scipy.html, Sec. 1.6.6.3.

from scipy import stats

x = np.random.normal(loc=0, scale=1, size=500)
y = np.random.normal(loc=0.1, scale=0.8, size=500)
stats.ttest_ind(x, y)

Ttest_indResult(statistic=-2.826692486177917, pvalue=0.00479708462987112)