# Data Science Academy / Week 5 Homework
# Titus Teodorescu

Part 1
--------------
Read and run the examples in the examples folder.


Part 2
--------------

Load PSTRE_syntheticData.csv

In [1]:
# import libraries
import numpy as np
import pandas as pd

# read the data ans store it in variable df
# despite the ".csv" name (which suggests the data is separated by commas), the separator in the source .csv file is a tab
df = pd.read_csv('data for week5/PSTRE_syntheticData.csv', sep='\t')
df

TestTakerID  Timestamp     Coding
0          1001042          0      START
1          1001042      44985      SS_Se
2          1001042      55852   SS_Se_OK
3          1001042      55950  SS_Type_2
4          1001042      66546          E
...            ...        ...        ...
10991      4076375      82216         SS
10992      4076375     107365          E
10993      4076375     112452       Next
10994      4076375     113670    Next_OK
10995      4076375     113672        END

[10996 rows x 3 columns]

* Create two new variables: action sequence variable and time interval sequence for each participant

In [2]:
list_with_new_variables = [(tt_id, event["Coding"].values[:-1], np.diff(event["Timestamp"].values)) for tt_id, event in list(df.groupby("TestTakerID"))]

# display the first 3
list_with_new_variables[0:3]

[(1001042,
  array(['START', 'SS_Se', 'SS_Se_OK', 'SS_Type_2', 'E', 'SS', 'E', 'Next',
         'Next_OK'], dtype=object),
  array([44985, 10867,    98, 10596, 23643,  5907,  5717,  3566,     3],
        dtype=int64)),
 (1001079,
  array(['START', 'SS_So', 'SS_So_1B', 'SS_So_OK', 'SS', 'E', 'SS', 'E',
         'SS', 'E', 'SS', 'E', 'E', 'Next', 'Next_OK'], dtype=object),
  array([21234,  6312,  4360, 45854, 29414,  7759,  5157,  4319,  1650,
         41297,  6090,  5651, 13227,  1791,     2], dtype=int64)),
 (1001103,
  array(['START', 'SS_Se', 'SS_Se_OK', 'SS_Type_2', 'E', 'SS', 'E', 'SS',
         'E', 'Next', 'Next_OK'], dtype=object),
  array([39002, 17605,   123, 31895,  4232, 31629, 18241,  7863, 19695,
          1672,     1], dtype=int64))]

* Extract the time for the first action for each participant

In [3]:
duration_of_first_action = [(tt_id, event["Timestamp"].values[1]-event["Timestamp"].values[0]) for tt_id, event in list(df.groupby("TestTakerID"))]

# display the first 10
duration_of_first_action[0:10]

[(1001042, 44985),
 (1001079, 21234),
 (1001103, 39002),
 (1001112, 54895),
 (1002087, 158089),
 (1002110, 93106),
 (1003077, 53204),
 (1003110, 18045),
 (1003147, 110606),
 (1003165, 89372)]

* Represent each action sequence by n-grams (n=2)

In [4]:
action_sequence_of_2_grams = [(tt_id, list(zip(event["Coding"].values[:-1], event["Coding"].values[1:]))) for tt_id, event in list(df.groupby("TestTakerID"))]

#display the first 3
action_sequence_of_2_grams[0:3]

[(1001042,
  [('START', 'SS_Se'),
   ('SS_Se', 'SS_Se_OK'),
   ('SS_Se_OK', 'SS_Type_2'),
   ('SS_Type_2', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'Next'),
   ('Next', 'Next_OK'),
   ('Next_OK', 'END')]),
 (1001079,
  [('START', 'SS_So'),
   ('SS_So', 'SS_So_1B'),
   ('SS_So_1B', 'SS_So_OK'),
   ('SS_So_OK', 'SS'),
   ('SS', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'E'),
   ('E', 'Next'),
   ('Next', 'Next_OK'),
   ('Next_OK', 'END')]),
 (1001103,
  [('START', 'SS_Se'),
   ('SS_Se', 'SS_Se_OK'),
   ('SS_Se_OK', 'SS_Type_2'),
   ('SS_Type_2', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'SS'),
   ('SS', 'E'),
   ('E', 'Next'),
   ('Next', 'Next_OK'),
   ('Next_OK', 'END')])]